export const ACTIONS = {
   ADD_TODO: 'ADD_TODO',
   REMOVE_TODO: 'REMOVE_TODO',
   TOGGLE_TODO: 'TOGGLE_TODO',
   RECEIVE_TODOS: 'RECEIVE_TODOS',
   SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER'
};

export const VisibilityFilters = {
  SHOW_ALL: 'SHOW_ALL',
  SHOW_COMPLETED: 'SHOW_COMPLETED',
  SHOW_ACTIVE: 'SHOW_ACTIVE'
}
