export const ACTIONS = {
   ADD_TODO: 'ADD_TODO',
   REMOVE_TODO: 'REMOVE_TODO',
   TOGGLE_TODO: 'TOGGLE_TODO',
   FETCH_TODOS_REQUEST: 'REQUEST_TODOS',
   FETCH_TODOS_SUCCESS: 'RECEIVE_TODOS',
   FETCH_TODOS_ERROR: 'FETCH_TODOS_FAILED',
   SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER'
};

export const VisibilityFilters = {
  SHOW_ALL: 'SHOW_ALL',
  SHOW_COMPLETED: 'SHOW_COMPLETED',
  SHOW_ACTIVE: 'SHOW_ACTIVE'
}
